#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib:/usr/lib
runlevel=S
umask 022
export PATH LD_LIBRARY_PATH runlevel

mount -a
mkdir /dev/pts
mount -t devpts devpts /dev/pts

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

cd /usr/bin
./lcd_always_on
cd ..

vsftpd &
/sbin/sshd &

if [ -f "/var/lib/alsa/asound.state" ]; then
	echo "ALSA: Restoring mixer setting......"
	/sbin/alsactl -f /var/lib/alsa/asound.state restore &
fi
